### PR TITLE
fix(scripts): if glog is not installed locally, build it from source.

### PR DESCRIPTION
**Pull request by haruhi55**
This PR improves the build process to make building TiledCUDA more automatic. The goal is to complete the build from scratch without any manual intervention.

1. The current version requires a locally installed glog; otherwise, users need to install it themselves. This PR addresses this issue by building glog from source if it is not installed locally. resolve https://github.com/TiledTensor/TiledCUDA/issues/62
1. Enhance CMake to locate the Torch library.

### CODE REVIEW

**Review by KuangjuX — COMMENTED** [review]
LGTM overall, but I wonder if it would be a better choice to explicitly place `glog` in `third-party` as submodule?  I'm not very clear on whether there are specific standards for how C++ introduces third-party libraries.

**Comment by haruhi55** [comment]
> LGTM overall, but I wonder if it would be a better choice to explicitly place `glog` in `third-party` as submodule? I'm not very clear on whether there are specific standards for how C++ introduces third-party libraries.

I think it's feasible if we choose to do so, as CMake is a scripting language. Similar to how gtest is currently added to dependencies as submodules without building, but glog requires building.
https://github.com/TiledTensor/TiledCUDA/blob/13e789a587c17b50e37b1822f8b6fda4b8c225a8/scripts/cmake/dependencies.cmake#L6-L8

Therefore, an additional out-of-source configuration and build process would be needed. Based on my past habits, an external project that requires configuration and building is added using `ExternalProject_Add`.

**Comment by KuangjuX** [comment]
> Therefore, an additional out-of-source configuration and build process would be needed. Based on my past habits, an external project that requires configuration and building is added using `ExternalProject_Add`.

Got it！

**Review by KuangjuX — APPROVED** [review]
LGTM

**Pull request merged**
